prepare versioned release

diff --git a/.github/workflows/docker-tagged-push.yml b/.github/workflows/docker-tagged-push.yml
--- a/.github/workflows/docker-tagged-push.yml
+++ b/.github/workflows/docker-tagged-push.yml
@@ -15,22 +15,22 @@ jobs:
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
-
-    - name: 🔍 DEBUG: Check if secrets exist
-      run: |
-        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
-          echo " DOCKERHUB_USERNAME is missing!"
-          exit 1
-        else
-          echo " DOCKERHUB_USERNAME exists."
-        fi
-
-        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
-          echo " DOCKERHUB_TOKEN is missing!"
-          exit 1
-        else
-          echo " DOCKERHUB_TOKEN exists."
-        fi
+    #
+    # - name: 🔍 DEBUG: Check if secrets exist
+    #   run: |
+    #     if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+    #       echo " DOCKERHUB_USERNAME is missing!"
+    #       exit 1
+    #     else
+    #       echo " DOCKERHUB_USERNAME exists."
+    #     fi
+    #
+    #     if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+    #       echo " DOCKERHUB_TOKEN is missing!"
+    #       exit 1
+    #     else
+    #       echo " DOCKERHUB_TOKEN exists."
+    #     fi
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v3.1.0
